### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by soltani123-Bilel** [stamakro/GCN-for-Structure-and-Function#11]
how can i run the project please 
thanks

**Comment by soltani123-Bilel** [comment]
the steps to run projrcts

**Comment by amelvim** [comment]
Hi!

For the PDB dataset, you can download the data, features and trained models from:
https://doi.org/10.4121/uuid:b88d84e1-7408-40d9-a8fc-d734f852dd7a

Then you can run our models using the scripts `Run_BASELINE.sh`, `Run_MLP.sh`, `Run_conv.sh`, or `Run_graphconv.sh` with the argument `$SET` equal to `pdb`. For example, to train the MLP model using ELMo embeddings you should specify the following arguments: `./Run_MLP.sh pdb embeddings train`.
You can also test our MLP trained model with: `./Run_MLP.sh pdb embeddings test`

Let me know if you have any other question.

**Comment by soltani123-Bilel** [comment]
can you explain to me more the steps to run you project please and where i should put the datset 
thanks

**Comment by soltani123-Bilel** [comment]
my objectif is  to predict protein function 
so tell me how can i realise this objectif by using your project

**Comment by Wenjian-Ma** [comment]
Hi!
I have some questions, may I have ur answer?
Pretrained ELMo is designed for protein function prediction? 
Have you ever try other pretrained protein language models for constructing residue-level features to predict protein function?
                                                                                                                                                            Thanks so much!

**Comment by stamakro** [comment]
Hi XXXXXcoder, no, pretrained elmo is not designed for predicting function, check the publication by Heinzinger et al. There are several papers using protein embeddings in all sorts of applications, a brief literature search will answer your questions.
